web/router.ex
defmodule Discuss.Router do
  use Discuss.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Discuss.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Discuss do
    pipe_through :browser # Use the default browser stack
    # get "/", TopicController, :index
    # get "/topics/new", TopicController, :new
    # get "/topics/:id/edit", TopicController, :edit
    # put "/topics/:id", TopicController, :update
    # delete "/topics/:id", TopicController, :delete
    # post "/topics", TopicController, :create
    resources "/", TopicController
  end

  scope "/auth", Discuss do
    pipe_through :browser
    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", Discuss do
  #   pipe_through :api
  # end
end

lib/discuss/endpoint.ex
defmodule Discuss.Endpoint do
  use Phoenix.Endpoint, otp_app: :discuss

  socket "/socket", Discuss.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :discuss, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_discuss_key",
    signing_salt: "C/quaETx"

  plug Discuss.Router
end

lib/discuss/repo.ex
defmodule Discuss.Repo do
  use Ecto.Repo, otp_app: :discuss
end

web/models/comment.ex
defmodule Discuss.Comment do
  use Discuss.Web, :model

  schema "comments" do
    field :content, :string
    belongs_to :user, Discuss.User
    belongs_to :topic, Discuss.Topic

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:content])
    |> validate_required([:content, :user, :topic])
  end
end

web/models/topic.ex
defmodule Discuss.Topic do
  use Discuss.Web, :model

  schema "topics" do
    field :title, :string
    belongs_to :user, Discuss.User
    has_many :comments, Discuss.Comment
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title])
    |> validate_required([:title])
  end
end

web/models/user.ex
defmodule Discuss.User do
  use Discuss.Web, :model

  schema "users" do
    field :email, :string
    field :provider, :string
    field :token, :string
    has_many :topics, Discuss.Topic
    has_many :comments, Discuss.Comment

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:email, :provider, :token])
    |> validate_required([:email, :provider, :token])
  end

end

web/controllers/page_controller.ex
defmodule Discuss.PageController do
  use Discuss.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/topic_controller.ex
defmodule Discuss.TopicController do
  use Discuss.Web, :controller

  alias Discuss.Topic

  plug Discuss.Plugs.RequireAuth when action in [:new, :create, :edit, :update,
                                                 :delete]
  plug :check_topic_owner when action in [:update, :edit, :delete]

  def check_topic_owner(conn, _params) do
    %{params: %{"id" => topic_id}} = conn
    if Repo.get(Topic, topic_id).user_id == conn.assigns.user.id do
      conn
    else
      conn
      |> put_flash(:error, "You do not have permissions for that action")
      |> redirect(to: topic_path(conn, :index))
      |> halt()
    end
  end

  def index(conn, _params) do
    topics = Repo.all(from Topic, order_by: [desc: :id])
    render conn, "index.html", topics: topics
  end

  def show(conn, %{"id" => topic_id}) do
    topic = Repo.get!(Topic, topic_id)
    render conn, "show.html", topic: topic
  end

  def new(conn, _params) do
    changeset = Topic.changeset(%Topic{}, %{})
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"topic" => topic}) do
    changeset = Ecto.build_assoc(conn.assigns.user, :topics)
    |> Topic.changeset(topic)

    case Repo.insert(changeset) do
      {:ok, _topic} ->
        conn
        |> put_flash(:info, "Topic created")
        |> redirect(to: topic_path(conn, :index))
      {:error, changeset} ->
        conn
        |> put_flash(:error, "Error creating topic")
        |> render("new.html", changeset: changeset)
    end
  end

  def edit(conn, %{"id" => topic_id}) do
    topic = Repo.get(Topic, topic_id)
    changeset = Topic.changeset(topic)
    render conn, "edit.html", changeset: changeset, topic: topic
  end

  def update(conn, %{"id" => topic_id, "topic" => topic}) do
    existing_topic = Repo.get(Topic, topic_id)
    changeset = Topic.changeset(existing_topic, topic)

    case Repo.update(changeset) do
      {:ok, _topic} ->
        conn
        |> put_flash(:info, "Topic updated")
        |> redirect(to: topic_path(conn, :index))
      {:error, changeset} ->
        conn
        |> put_flash(:error, "Error updating topic")
        |> render("edit.html", changeset: changeset, topic: existing_topic)
    end
  end

  def delete(conn, %{"id" => topic_id}) do
    topic = Repo.get(Topic, topic_id)
    changeset = Topic.changeset(topic)

    case Repo.delete(changeset) do
      {:ok, _topic} ->
        conn
        |> put_flash(:info, "Topic deleted")
        |> redirect(to: topic_path(conn, :index))
      {:error, _changeset} ->
        conn
        |> put_flash(:error, "Error deleting topic")
        |> redirect(to: topic_path(conn, :index))
    end
  end

end

web/views/error_view.ex
defmodule Discuss.ErrorView do
  use Discuss.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Discuss.LayoutView do
  use Discuss.Web, :view
end

web/views/page_view.ex
defmodule Discuss.PageView do
  use Discuss.Web, :view
end

web/views/topic_view.ex
defmodule Discuss.TopicView do
  use Discuss.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <!-- Which one of you was curious enough to check out my HTML source? :p -->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TalkToEmma - Hello from Emma!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

  <body>
    <ul id="user-menu" class="dropdown-content">
      <%= if @conn.assigns[:user] do %>
        <li>
          <%= link to: auth_path(@conn, :signout) do %>
            Sign out
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link to: auth_path(@conn, :request, :google) do %>
            ...using Google
          <% end %>
        </li>
        <li>
          <%= link to: auth_path(@conn, :request, :github) do %>
            ...using GitHub
          <% end %>
        </li>
      <% end %>
    </ul>
    <nav class="top-bar light-blue">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo left">
          TalkToEmma
        </a>
        <ul class="right">
          <li>
            <a class="dropdown-button account" href="#!" data-activates="user-menu">
              <%= if @conn.assigns[:user] do %>
                <i class="material-icons account left">account_circle</i>&nbsp;
                <i class="material-icons account right">arrow_drop_down</i>
              <% else %>
                Sign in...<i class="material-icons account right">arrow_drop_down</i>
              <% end %>
            </a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info chip blue lighten-2" role="alert">
          <%= get_flash(@conn, :info) %>
        </p>
      <% end %>
      <%= if get_flash(@conn, :error) do %></p>
        <p class="alert alert-danger chip red lighten-2" role="alert">
          <span class="left">
            <i class="material-icons">error_outline</i>
          </span>
          <%= get_flash(@conn, :error) %>
        </p>
      <% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://google.com">Google</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/topic/edit.html.eex
<%= form_for @changeset, topic_path(@conn, :update, @topic), fn f -> %>
  <div class="form-group">
    <div class="input-field">
      <%= text_input f, :title, class: "form_control" %>
      <%= label :topic, :title, class: "active" %>
    </div>
    <%= error_tag f, :title %>
  </div>
  <%= submit "Save Topic", class: "btn btn-primary" %>
  <%= link to: topic_path(@conn, :index), \
           class: "btn red waves-effect waves-light" do %>
    Cancel
  <% end %>
<% end %>

web/templates/topic/index.html.eex
<h5 class="main-title">Topics</h5>
<%= for topic <- @topics do %>
<div class="row topic-item">
  <div class="card">
    <div class="id-number left card-content blue white-text">
      <%= topic.id %>
    </div>
    <div class="card-content">
      <%= if @conn.assigns.user && @conn.assigns.user.id == topic.user_id do %>
        <div class="right">
          <%= link to: topic_path(@conn, :edit, topic), \
                   class: "waves-effect waves-light btn-small" do %>
            <i class="material-icons">mode_edit</i>
          <% end %> &nbsp;
          <%= link to: topic_path(@conn, :delete, topic), method: :delete, \
                   class: "waves-effect waves-light btn-small" do %>
            <i class="material-icons">delete</i>
          <% end %>
        </div>
      <% end %>
      <%= link topic.title, to: topic_path(@conn, :show, topic) %>
    </div>
  </div>
</div>
<% end %>

<div class="fixed-action-btn">
  <%= link to: topic_path(@conn, :new), \
           class: "btn-floating btn-large waves-effect waves-light red" do %>
    <i class="material-icons">add</i>
  <% end %>
</div>

web/templates/topic/new.html.eex
<%= form_for @changeset, topic_path(@conn, :create), fn f -> %>
  <div class="form-group">
    <div class="input-field">
      <%= text_input f, :title, class: "form_control" %>
      <%= label :topic, :title %>
    </div>
    <%= error_tag f, :title %>
  </div>
  <%= submit "Save Topic", class: "btn btn-primary" %>
  <%= link to: topic_path(@conn, :index), \
           class: "btn red waves-effect waves-light" do %>
    Cancel
  <% end %>
<% end %>

web/templates/topic/show.html.eex
<div class="row">
  <div class="card">
    <div class="id-number left card-content blue white-text">
      <%= @topic.id %>
    </div>
    <div class="card-content">
      <%= @topic.title %>
    </div>
  </div>
</div>

<div class="fixed-action-btn">
  <%= link to: topic_path(@conn, :new), \
           class: "btn-floating btn-large waves-effect waves-light red" do %>
    <i class="material-icons">add</i>
  <% end %>
</div>